@startuml modeloArquitetura
  component "View"{
    [<<view>> Componente de Jogo]
    [<<view>> Componente de Configuração do Jogo]
    [<<view>> Componente de Estatísticas]
  }
  component "controller"{
    [<<controller>> Componente de Jogo]
    [<<controller>> Componente de Configuração do Jogo]
    [<<controller>> Componente de Estatísticas]
  }

  component "Model"{
    [Componente de Acesso à Database de Estatísticas]
  }

  database "Database de Jogos" as db

  [<<controller>> Componente de Jogo] --> [<<view>> Componente de Jogo] : Atualiza
  [<<controller>> Componente de Configuração do Jogo] --> [<<view>> Componente de Configuração do Jogo] : Atualiza
  [<<controller>> Componente de Estatísticas] --> [<<view>> Componente de Estatísticas] : Atualiza

  [<<controller>> Componente de Jogo] --> [<<controller>> Componente de Configuração do Jogo] : Utiliza
  [<<controller>> Componente de Estatísticas] --> [<<controller>> Componente de Jogo] : Utiliza

  [<<controller>> Componente de Jogo] <-- [<<view>> Componente de Jogo] : Ação
  [<<controller>> Componente de Configuração do Jogo] <-- [<<view>> Componente de Configuração do Jogo] : Ação
  [<<controller>> Componente de Estatísticas] <-- [<<view>> Componente de Estatísticas] : Ação

  [<<controller>> Componente de Estatísticas] <-- [Componente de Acesso à Database de Estatísticas] : Notifica
  [<<controller>> Componente de Estatísticas] --> [Componente de Acesso à Database de Estatísticas] : Atualiza
  [<<controller>> Componente de Jogo] <-- [Componente de Acesso à Database de Estatísticas] : Notifica
  [<<controller>> Componente de Jogo] --> [Componente de Acesso à Database de Estatísticas] : Atualiza

  db <--> [Componente de Acesso à Database de Estatísticas] : CRUD \\ Acessa




actor "Jogador Convidado" as Player
actor "Jogador Administrador" as Admin
actor "Desenvolvedor" as Dev

Player --> [<<view>> Componente de Jogo]

Admin --> [<<view>> Componente de Configuração do Jogo]
Admin --> [<<view>> Componente de Jogo]

Dev --> [<<view>> Componente de Estatísticas]

' Integrantes
'note as N
  'Guilherme Lorete Schmidt - 13676857
  'Luana Hartmann Franco da Cruz - 13676350
  'João Pedro Gomes - 13839069
'end note

@enduml